### ISSUE TITLE
propery should probably be property

### ISSUE THREAD

**Issue by willielassiter** [DivineDominion/mac-appdev-book#6]
Box`is an **Aggregate** with a title propery and a collection of`Item`s. It's an **Entity** inasmuch as it has identity over time. The user should be able to change the title of existing`Box`es later on. That's sufficient to make it an **Entity**.

**Comment by DivineDominion** [comment]
Fixed. Thanks for reporting! Tell me how you liked the book when you're done so I can make it better!

**Comment by willielassiter** [comment]
will do, and there is something wrong with the following sentence, but i don't know what.

You can change an easy-to-grasp view model to make the view with all its complex components change. A presenter hides away the complexity of the user interface and requires data only. To the client code, the rest happens magically.

**Comment by DivineDominion** [comment]
Thanks!

You are right. I got rid of parts of the sentence.
